### PR TITLE
Fix invalid typescript module path

### LINKED ISSUE #18: Vue3 Typescript not working
Hi,

Is it me or i'm missing something here  `package.json` revers to a `.ts` which does not exists

https://github.com/davestewart/vue-class-store/blob/feature/vue-3/package.json#L8

And your build script generates a `.js`

https://github.com/davestewart/vue-class-store/blob/master/build/rollup.js#L65

Thanks

### PR DESCRIPTION
**Pull request by sadortun**
@davestewart Tested, and this fix #18

### CODE REVIEW

**Comment by davestewart** [comment]
Nice one. I have to find the time to publish (it's a one-liner, but just to be sure).

You OK waiting a few days?

**Comment by sadortun** [comment]
Yeah, I got it rebuild in a branch my fork

**Comment by djmaze** [comment]
Just stumbled upon this as well. Would be nice if a new version could be published.

**Comment by davestewart** [comment]
OK. This is on my list for tomorrow morning. Sorry for the wait!

**Pull request merged**
